# Generated by Django 2.2.10 on 2021-07-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=20)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='', max_length=20)),
                ('updated_by', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(default='', max_length=8)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('contact', models.EmailField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(default='yaozeliang', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('success', 'Create'), ('warning', 'Update'), ('danger', 'Delete')], default='success', max_length=20)),
                ('target_model', models.CharField(default='', max_length=20)),
                ('detail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d/')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='Author')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_borrow_times', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=10)),
                ('status', models.IntegerField(choices=[(0, 'On loan'), (1, 'In Stock')], default=1)),
                ('floor_number', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], default=1)),
                ('bookshelf_number', models.CharField(default='0001', max_length=10, verbose_name='Bookshelf Number')),
                ('updated_by', models.CharField(default='yaozeliang', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='book.Category')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to='book.Publisher')),
            ],
        ),
    ]
