# Generated by Django 2.2.10 on 2021-08-02 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Open"), (1, "Closed")], default=0
                    ),
                ),
                (
                    "return_on_time",
                    models.BooleanField(
                        choices=[(True, "On Time"), (False, "Delayed")], default=True
                    ),
                ),
                ("delay_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(default="", max_length=20)),
                ("updated_by", models.CharField(default="", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                # Names, not foreign keys. book_name is renamed to book in 0004.
                # Integer FK columns cannot reference book_book.id after a later
                # cast to varchar, which Postgres rejects.
                ("book_name", models.CharField(max_length=20)),
                ("borrower", models.CharField(max_length=20)),
            ],
        ),
    ]
