# Generated by Django 2.2.10 on 2021-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210705_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quatntity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
