# Generated by Django 2.2.10 on 2021-08-02 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210802_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='book_name',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 17, 43, 8, 210174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
