# Generated by Django 2.2.10 on 2021-07-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_quatntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quatntity',
            new_name='quantity',
        ),
    ]
