# Generated by Django 2.2.10 on 2021-08-03 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210802_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrower',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 18, 10, 53, 791692, tzinfo=utc)),
        ),
    ]
