# Generated by Django 2.2.10 on 2021-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210721_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf_number',
            field=models.CharField(default='0001', max_length=10, verbose_name='Bookshelf Number'),
        ),
        migrations.AddField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor')], default=1),
        ),
    ]
