# Generated by Django 2.2.10 on 2021-08-03 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210803_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrower_card',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 18, 43, 35, 910556, tzinfo=utc)),
        ),
    ]
