# Generated by Django 2.2.10 on 2021-07-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210721_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.CharField(default='yaozeliang', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='book.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '1st '), (2, '2nd '), (3, '3rd ')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to='book.Publisher'),
        ),
    ]
