# Generated by Django 2.2.10 on 2021-08-04 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210803_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='periode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='created_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 17, 36, 4, 880106, tzinfo=utc)),
        ),
    ]
