# Generated by Django 2.2.10 on 2021-08-09 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210804_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 8, 55, 47, 403001, tzinfo=utc)),
        ),
    ]
