# Generated by Django 2.2.10 on 2021-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210722_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
