# Generated by Django 2.2.10 on 2021-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210722_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], default=1),
        ),
    ]
