# Generated by Django 2.2.10 on 2021-08-09 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210809_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='return_on_time',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 18, 6, 49, 203445, tzinfo=utc)),
        ),
    ]
