# Generated by Django 2.2.10 on 2021-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210725_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='target_model',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='operation_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Add'), (2, 'Update'), (3, 'Delete')], default=0),
        ),
    ]
