# Generated by Django 2.2.10 on 2021-08-10 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210810_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='updated_at',
            new_name='closed_at',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 19, 12, 47, 275402, tzinfo=utc)),
        ),
    ]
