# Generated by Django 2.2.10 on 2021-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210725_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='detail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
