# Generated by Django 2.2.10 on 2021-08-10 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210810_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 27, 43, 661499, tzinfo=utc)),
        ),
    ]
