# Generated by Django 2.2.10 on 2021-07-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_useractivity_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='operation_type',
            field=models.IntegerField(choices=[('success', 'Create'), ('warning', 'Update'), ('danger', 'Delete')], default=0),
        ),
    ]
