# Generated by Django 2.2.10 on 2021-08-11 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20210810_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 21, 3, 37, 983009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='operation_type',
            field=models.CharField(choices=[('success', 'Create'), ('warning', 'Update'), ('danger', 'Delete'), ('info', 'Close')], default='success', max_length=20),
        ),
    ]
