# Generated by Django 2.2.10 on 2021-07-26 15:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 17, 30, 2, 526883)),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
