# Generated by Django 2.2.10 on 2021-07-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20210726_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='member',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 19, 28, 27, 799756)),
        ),
    ]
