# Generated by Django 2.2.10 on 2021-07-26 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20210726_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 19, 33, 16, 671337)),
        ),
    ]
