# Generated by Django 2.2.10 on 2021-07-26 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20210726_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 19, 37, 47, 24812)),
        ),
    ]
