# Generated by Django 2.2.10 on 2021-08-15 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20210812_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='final_status',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 16, 42, 4, 542779, tzinfo=utc)),
        ),
    ]
