# Generated by Django 2.2.10 on 2021-08-16 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_auto_20210815_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 8, 45, 11, 620480, tzinfo=utc)),
        ),
    ]
