# Generated by Django 2.2.10 on 2021-08-16 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20210816_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 8, 45, 31, 317281, tzinfo=utc)),
        ),
    ]
