# Generated by Django 2.2.10 on 2021-07-26 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20210726_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 2, 3, 802221)),
        ),
    ]
