# Generated by Django 2.2.10 on 2021-07-27 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20210726_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='modify_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 20, 47, 43, 149208)),
        ),
    ]
