# Generated by Django 2.2.10 on 2021-08-16 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20210816_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 9, 31, 29, 691873, tzinfo=utc)),
        ),
    ]
