# Generated by Django 2.2.10 on 2021-07-27 19:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20210727_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 21, 13, 4, 464464)),
        ),
    ]
