# Generated by Django 2.2.10 on 2021-08-25 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20210816_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 17, 56, 34, 718543, tzinfo=utc)),
        ),
    ]
