# Generated by Django 2.2.10 on 2021-07-27 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20210727_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='created_by',
            new_name='create_by',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='modified_at',
            new_name='modify_at',
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 22, 7, 51, 570032)),
        ),
    ]
