# Generated by Django 2.2.10 on 2021-08-25 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20210825_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 18, 26, 3, 755494, tzinfo=utc)),
        ),
    ]
