# Generated by Django 2.2.10 on 2021-08-27 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_auto_20210825_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 18, 55, 30, 923271, tzinfo=utc)),
        ),
    ]
