# Generated by Django 2.2.10 on 2021-08-27 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20210827_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 19, 44, 35, 459382, tzinfo=utc)),
        ),
    ]
