# Generated by Django 2.2.10 on 2021-12-26 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_auto_20210827_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 11, 55, 30, 383234, tzinfo=utc)),
        ),
    ]
