# Generated by Django 2.2.10 on 2021-12-26 14:29

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0031_auto_20211226_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="end_day",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 2, 14, 29, 39, 914330, tzinfo=utc)
            ),
        ),
    ]
