# Generated by Django 2.2.10 on 2021-07-27 20:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_auto_20210727_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 22, 46, 9, 885777)),
        ),
    ]
