# Generated by Django 2.2.10 on 2025-07-12 21:33

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0032_auto_20211226_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="end_day",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 19, 21, 33, 7, 142261, tzinfo=utc)
            ),
        ),
    ]
