# Generated by Django 2.2.10 on 2025-07-12 22:18

import datetime

from django.db import migrations, models
from datetime import timezone

utc = timezone.utc


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0033_auto_20250712_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="end_day",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 19, 22, 18, 58, 369504, tzinfo=utc)
            ),
        ),
    ]
