# Generated by Django 2.2.10 on 2025-07-31 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20250713_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 18, 58, 2, 182119, tzinfo=utc)),
        ),
    ]
