# Generated by Django 2.2.10 on 2021-07-27 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20210727_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='modify_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='modify_by',
            new_name='updated_by',
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 22, 57, 55, 552434)),
        ),
    ]
