# Generated by Django 2.2.10 on 2021-07-27 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20210727_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 23, 10, 33, 111025)),
        ),
    ]
