# Generated by Django 5.2.17 on 2026-09-24 07:12

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20250731_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=book.models.default_borrow_end_day),
        ),
    ]
