# Generated by Django 5.2.17 on 2026-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_borrowrecord_end_day_callable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.CharField(max_length=100),
        ),
    ]
