# Generated by Django 2.2.10 on 2021-07-28 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_auto_20210728_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 23, 25, 30, 590408)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d/'),
        ),
    ]
